id: org.termx.cda2fhir
canonical: https://termx.org/cda2fhir
name: CDA to FHIR transformations
title: CDA to FHIR transformations
status: draft
version: 1.0.0
fhirVersion: 5.0.0
copyrightYear: 2024+
releaseLabel: ballot
publisher: 
  name: TermX